from selenium import webdriver
driver = webdriver.Chrome()
driver.maximize_window()

driver.get("http://practice.automationtesting.in/")
driver.execute_script("window.scrollBy(0,600);")
selenium_ruby = driver.find_element_by_css_selector("[title='Selenium Ruby']")
selenium_ruby.click()
reviews = driver.find_element_by_class_name("reviews_tab")
reviews.click()
star = driver.find_element_by_class_name("star-5")
star.click()
comment = driver.find_element_by_id("comment")
comment.send_keys("Nice book!")
name = driver.find_element_by_id("author")
name.send_keys("Ivan")
email = driver.find_element_by_id("email")
email.send_keys("123@123.com")
submit = driver.find_element_by_id("submit")
submit.click()